name: Spec
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Build Image
        run: docker build -t or13/markdown2rfc ./docker

      - name: Build Spec
        run: ./spec/build.sh

      - name: Deploy Spec
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
